package forpleuvoir.dhwu1a.core.common

/**
 * @author forpleuvoir
 *
 * #project_name dhwu1a
 *
 * #package forpleuvoir.dhwu1a.core.common
 *
 * #class_name ApiKey
 *
 * #create_time 2021/4/13 13:41
 */
const val AUTH_KEY = "authKey"
const val VERIFY_KEY = "verifyKey"
const val CODE = "code"
const val CONTENT = "content"
const val FRIEND = "friend"
const val VALUE = "value"
const val INPUTTING = "inputting"
const val PLATFORM = "platform"
const val FROM = "from"
const val HONOR = "honor"
const val TO = "to"
const val COMMAND = "command"
const val JOIN_TIMESTAMP = "joinTimestamp"
const val LAST_SPEAK_TIMESTAMP = "lastSpeakTimestamp"
const val MUTE_TIME_REMAINING = "muteTimeRemaining"
const val SUB_COMMAND = "subCommand"
const val SYNC_ID = "syncId"
const val EVENT = "event"
const val ALL = "all"
const val EMAIL = "email"
const val AGE = "age"
const val LEVEL = "level"
const val SEX = "sex"
const val SIGN = "sign"
const val MSG = "msg"
const val SESSION = "session"
const val SESSION_KEY = "sessionKey"
const val QQ = "qq"
const val TYPE = "type"
const val ID = "id"
const val TIME = "time"
const val TEXT = "text"
const val MESSAGE_CHAIN = "messageChain"
const val SENDER = "sender"
const val MEMBER_NAME = "memberName"
const val PERMISSION = "permission"
const val GROUP = "group"
const val NAME = "name"
const val GROUP_ID = "groupId"
const val SENDER_ID = "senderId"
const val TARGET_ID = "targetId"
const val ORIGIN = "origin"
const val DISPLAY = "display"
const val TARGET = "target"
const val MEMBER_ID = "memberId"
const val FACE_ID = "faceId"
const val IMAGE_ID = "imageId"
const val URL = "url"
const val BASE64 = "base64"
const val PATH = "path"
const val VOICE_ID = "voiceId"
const val XML = "xml"
const val JSON = "json"
const val TITLE = "title"
const val BRIEF = "brief"
const val SOURCE = "source"
const val SUMMARY = "summary"
const val NODE_LIST = "nodeList"
const val SENDER_NAME = "senderName"
const val INTERNAL_ID = "internalId"
const val SIZE = "size"
const val NICKNAME = "nickname"
const val REMARK = "remark"
const val MESSAGE_ID = "messageId"
const val PREVIEW = "preview"
const val NEW = "new"
const val CURRENT = "current"
const val DURATION_SECONDS = "durationSeconds"
const val OPERATOR = "operator"
const val AUTHOR_ID = "authorId"
const val IS_BY_BOT = "isByBot"
const val MEMBER = "member"
const val EVENT_ID = "eventId"
const val FROM_ID = "fromId"
const val NICK = "nick"
const val MESSAGE = "message"
const val GROUP_NAME = "groupName"
const val SUBJECT = "subject"
const val KIND = "kind"
const val ACTION = "action"
const val SUFFIX = "suffix"
const val ANNOUNCEMENT = "announcement"
const val CONFESS_TALK = "confessTalk"
const val ALLOW_MEMBER_INVITE = "allowMemberInvite"
const val AUTO_APPROVE = "autoApprove"
const val ANONYMOUS_CHAT = "anonymousChat"
const val SPECIAL_TITLE = "specialTitle"
const val QUOTE = "quote"
const val JUMP_URL = "jumpUrl"
const val PICTURE_URL = "pictureUrl"
const val MUSIC_URL = "musicUrl"
const val VERSION = "version"
const val DATA = "data"
const val ERROR_MESSAGE = "errorMessage"
